// Code generated by MockGen. DO NOT EDIT.
// Source: net.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "url-shortening-service/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockUrlDeleter is a mock of UrlDeleter interface.
type MockUrlDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockUrlDeleterMockRecorder
}

// MockUrlDeleterMockRecorder is the mock recorder for MockUrlDeleter.
type MockUrlDeleterMockRecorder struct {
	mock *MockUrlDeleter
}

// NewMockUrlDeleter creates a new mock instance.
func NewMockUrlDeleter(ctrl *gomock.Controller) *MockUrlDeleter {
	mock := &MockUrlDeleter{ctrl: ctrl}
	mock.recorder = &MockUrlDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlDeleter) EXPECT() *MockUrlDeleterMockRecorder {
	return m.recorder
}

// DeleteUrl mocks base method.
func (m *MockUrlDeleter) DeleteUrl(ctx context.Context, urlToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUrl", ctx, urlToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUrl indicates an expected call of DeleteUrl.
func (mr *MockUrlDeleterMockRecorder) DeleteUrl(ctx, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUrl", reflect.TypeOf((*MockUrlDeleter)(nil).DeleteUrl), ctx, urlToken)
}

// MockUrlGetter is a mock of UrlGetter interface.
type MockUrlGetter struct {
	ctrl     *gomock.Controller
	recorder *MockUrlGetterMockRecorder
}

// MockUrlGetterMockRecorder is the mock recorder for MockUrlGetter.
type MockUrlGetterMockRecorder struct {
	mock *MockUrlGetter
}

// NewMockUrlGetter creates a new mock instance.
func NewMockUrlGetter(ctrl *gomock.Controller) *MockUrlGetter {
	mock := &MockUrlGetter{ctrl: ctrl}
	mock.recorder = &MockUrlGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlGetter) EXPECT() *MockUrlGetterMockRecorder {
	return m.recorder
}

// GetOriginalUrl mocks base method.
func (m *MockUrlGetter) GetOriginalUrl(ctx context.Context, urlToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalUrl", ctx, urlToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalUrl indicates an expected call of GetOriginalUrl.
func (mr *MockUrlGetterMockRecorder) GetOriginalUrl(ctx, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalUrl", reflect.TypeOf((*MockUrlGetter)(nil).GetOriginalUrl), ctx, urlToken)
}

// MockUrlShortener is a mock of UrlShortener interface.
type MockUrlShortener struct {
	ctrl     *gomock.Controller
	recorder *MockUrlShortenerMockRecorder
}

// MockUrlShortenerMockRecorder is the mock recorder for MockUrlShortener.
type MockUrlShortenerMockRecorder struct {
	mock *MockUrlShortener
}

// NewMockUrlShortener creates a new mock instance.
func NewMockUrlShortener(ctrl *gomock.Controller) *MockUrlShortener {
	mock := &MockUrlShortener{ctrl: ctrl}
	mock.recorder = &MockUrlShortenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlShortener) EXPECT() *MockUrlShortenerMockRecorder {
	return m.recorder
}

// ShortenUrl mocks base method.
func (m *MockUrlShortener) ShortenUrl(ctx context.Context, originalUrl string) (domain.MappingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenUrl", ctx, originalUrl)
	ret0, _ := ret[0].(domain.MappingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenUrl indicates an expected call of ShortenUrl.
func (mr *MockUrlShortenerMockRecorder) ShortenUrl(ctx, originalUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenUrl", reflect.TypeOf((*MockUrlShortener)(nil).ShortenUrl), ctx, originalUrl)
}

// MockUrlUpdater is a mock of UrlUpdater interface.
type MockUrlUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockUrlUpdaterMockRecorder
}

// MockUrlUpdaterMockRecorder is the mock recorder for MockUrlUpdater.
type MockUrlUpdaterMockRecorder struct {
	mock *MockUrlUpdater
}

// NewMockUrlUpdater creates a new mock instance.
func NewMockUrlUpdater(ctrl *gomock.Controller) *MockUrlUpdater {
	mock := &MockUrlUpdater{ctrl: ctrl}
	mock.recorder = &MockUrlUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlUpdater) EXPECT() *MockUrlUpdaterMockRecorder {
	return m.recorder
}

// UpdateUrlMapping mocks base method.
func (m *MockUrlUpdater) UpdateUrlMapping(ctx context.Context, urlToken, newOriginalUrl string) (domain.MappingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUrlMapping", ctx, urlToken, newOriginalUrl)
	ret0, _ := ret[0].(domain.MappingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUrlMapping indicates an expected call of UpdateUrlMapping.
func (mr *MockUrlUpdaterMockRecorder) UpdateUrlMapping(ctx, urlToken, newOriginalUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUrlMapping", reflect.TypeOf((*MockUrlUpdater)(nil).UpdateUrlMapping), ctx, urlToken, newOriginalUrl)
}
