// Code generated by MockGen. DO NOT EDIT.
// Source: statistics.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "url-shortening-service/internal/domain"

	gomock "github.com/golang/mock/gomock"
	kafka "github.com/segmentio/kafka-go"
)

// MockStatisticsProcessor is a mock of StatisticsProcessor interface.
type MockStatisticsProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticsProcessorMockRecorder
}

// MockStatisticsProcessorMockRecorder is the mock recorder for MockStatisticsProcessor.
type MockStatisticsProcessorMockRecorder struct {
	mock *MockStatisticsProcessor
}

// NewMockStatisticsProcessor creates a new mock instance.
func NewMockStatisticsProcessor(ctrl *gomock.Controller) *MockStatisticsProcessor {
	mock := &MockStatisticsProcessor{ctrl: ctrl}
	mock.recorder = &MockStatisticsProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticsProcessor) EXPECT() *MockStatisticsProcessorMockRecorder {
	return m.recorder
}

// ProcessEvent mocks base method.
func (m *MockStatisticsProcessor) ProcessEvent(ctx context.Context, eventData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessEvent", ctx, eventData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessEvent indicates an expected call of ProcessEvent.
func (mr *MockStatisticsProcessorMockRecorder) ProcessEvent(ctx, eventData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessEvent", reflect.TypeOf((*MockStatisticsProcessor)(nil).ProcessEvent), ctx, eventData)
}

// MockStatsEventAdder is a mock of StatsEventAdder interface.
type MockStatsEventAdder struct {
	ctrl     *gomock.Controller
	recorder *MockStatsEventAdderMockRecorder
}

// MockStatsEventAdderMockRecorder is the mock recorder for MockStatsEventAdder.
type MockStatsEventAdderMockRecorder struct {
	mock *MockStatsEventAdder
}

// NewMockStatsEventAdder creates a new mock instance.
func NewMockStatsEventAdder(ctrl *gomock.Controller) *MockStatsEventAdder {
	mock := &MockStatsEventAdder{ctrl: ctrl}
	mock.recorder = &MockStatsEventAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsEventAdder) EXPECT() *MockStatsEventAdderMockRecorder {
	return m.recorder
}

// AddStatsEvent mocks base method.
func (m *MockStatsEventAdder) AddStatsEvent(ctx context.Context, event domain.ProcessedStatsEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStatsEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStatsEvent indicates an expected call of AddStatsEvent.
func (mr *MockStatsEventAdderMockRecorder) AddStatsEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStatsEvent", reflect.TypeOf((*MockStatsEventAdder)(nil).AddStatsEvent), ctx, event)
}

// MockStatisticsCalculator is a mock of StatisticsCalculator interface.
type MockStatisticsCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticsCalculatorMockRecorder
}

// MockStatisticsCalculatorMockRecorder is the mock recorder for MockStatisticsCalculator.
type MockStatisticsCalculatorMockRecorder struct {
	mock *MockStatisticsCalculator
}

// NewMockStatisticsCalculator creates a new mock instance.
func NewMockStatisticsCalculator(ctrl *gomock.Controller) *MockStatisticsCalculator {
	mock := &MockStatisticsCalculator{ctrl: ctrl}
	mock.recorder = &MockStatisticsCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticsCalculator) EXPECT() *MockStatisticsCalculatorMockRecorder {
	return m.recorder
}

// CalculateStatistics mocks base method.
func (m *MockStatisticsCalculator) CalculateStatistics(ctx context.Context, urlToken string) (domain.CalculatedStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateStatistics", ctx, urlToken)
	ret0, _ := ret[0].(domain.CalculatedStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateStatistics indicates an expected call of CalculateStatistics.
func (mr *MockStatisticsCalculatorMockRecorder) CalculateStatistics(ctx, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateStatistics", reflect.TypeOf((*MockStatisticsCalculator)(nil).CalculateStatistics), ctx, urlToken)
}

// MockStatisticsSender is a mock of StatisticsSender interface.
type MockStatisticsSender struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticsSenderMockRecorder
}

// MockStatisticsSenderMockRecorder is the mock recorder for MockStatisticsSender.
type MockStatisticsSenderMockRecorder struct {
	mock *MockStatisticsSender
}

// NewMockStatisticsSender creates a new mock instance.
func NewMockStatisticsSender(ctrl *gomock.Controller) *MockStatisticsSender {
	mock := &MockStatisticsSender{ctrl: ctrl}
	mock.recorder = &MockStatisticsSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticsSender) EXPECT() *MockStatisticsSenderMockRecorder {
	return m.recorder
}

// SendEvent mocks base method.
func (m *MockStatisticsSender) SendEvent(ctx context.Context, rawEvent domain.RawStatsEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEvent", ctx, rawEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockStatisticsSenderMockRecorder) SendEvent(ctx, rawEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockStatisticsSender)(nil).SendEvent), ctx, rawEvent)
}

// MockMessageFetcher is a mock of MessageFetcher interface.
type MockMessageFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockMessageFetcherMockRecorder
}

// MockMessageFetcherMockRecorder is the mock recorder for MockMessageFetcher.
type MockMessageFetcherMockRecorder struct {
	mock *MockMessageFetcher
}

// NewMockMessageFetcher creates a new mock instance.
func NewMockMessageFetcher(ctrl *gomock.Controller) *MockMessageFetcher {
	mock := &MockMessageFetcher{ctrl: ctrl}
	mock.recorder = &MockMessageFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageFetcher) EXPECT() *MockMessageFetcherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessageFetcher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMessageFetcherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessageFetcher)(nil).Close))
}

// CommitMessages mocks base method.
func (m *MockMessageFetcher) CommitMessages(ctx context.Context, msgs ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitMessages indicates an expected call of CommitMessages.
func (mr *MockMessageFetcherMockRecorder) CommitMessages(ctx interface{}, msgs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitMessages", reflect.TypeOf((*MockMessageFetcher)(nil).CommitMessages), varargs...)
}

// FetchMessage mocks base method.
func (m *MockMessageFetcher) FetchMessage(ctx context.Context) (kafka.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMessage", ctx)
	ret0, _ := ret[0].(kafka.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMessage indicates an expected call of FetchMessage.
func (mr *MockMessageFetcherMockRecorder) FetchMessage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMessage", reflect.TypeOf((*MockMessageFetcher)(nil).FetchMessage), ctx)
}

// MockMessageWriter is a mock of MessageWriter interface.
type MockMessageWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMessageWriterMockRecorder
}

// MockMessageWriterMockRecorder is the mock recorder for MockMessageWriter.
type MockMessageWriterMockRecorder struct {
	mock *MockMessageWriter
}

// NewMockMessageWriter creates a new mock instance.
func NewMockMessageWriter(ctrl *gomock.Controller) *MockMessageWriter {
	mock := &MockMessageWriter{ctrl: ctrl}
	mock.recorder = &MockMessageWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageWriter) EXPECT() *MockMessageWriterMockRecorder {
	return m.recorder
}

// WriteMessages mocks base method.
func (m *MockMessageWriter) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockMessageWriterMockRecorder) WriteMessages(ctx interface{}, msgs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockMessageWriter)(nil).WriteMessages), varargs...)
}
