// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "url-shortening-service/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockMappedGetSetter is a mock of MappedGetSetter interface.
type MockMappedGetSetter struct {
	ctrl     *gomock.Controller
	recorder *MockMappedGetSetterMockRecorder
}

// MockMappedGetSetterMockRecorder is the mock recorder for MockMappedGetSetter.
type MockMappedGetSetterMockRecorder struct {
	mock *MockMappedGetSetter
}

// NewMockMappedGetSetter creates a new mock instance.
func NewMockMappedGetSetter(ctrl *gomock.Controller) *MockMappedGetSetter {
	mock := &MockMappedGetSetter{ctrl: ctrl}
	mock.recorder = &MockMappedGetSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappedGetSetter) EXPECT() *MockMappedGetSetterMockRecorder {
	return m.recorder
}

// GetOriginalUrl mocks base method.
func (m *MockMappedGetSetter) GetOriginalUrl(ctx context.Context, shortUrl string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalUrl", ctx, shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetOriginalUrl indicates an expected call of GetOriginalUrl.
func (mr *MockMappedGetSetterMockRecorder) GetOriginalUrl(ctx, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalUrl", reflect.TypeOf((*MockMappedGetSetter)(nil).GetOriginalUrl), ctx, shortUrl)
}

// SetMapping mocks base method.
func (m *MockMappedGetSetter) SetMapping(ctx context.Context, originalUrl, urlToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMapping", ctx, originalUrl, urlToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMapping indicates an expected call of SetMapping.
func (mr *MockMappedGetSetterMockRecorder) SetMapping(ctx, originalUrl, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMapping", reflect.TypeOf((*MockMappedGetSetter)(nil).SetMapping), ctx, originalUrl, urlToken)
}

// MockMappingInfoGetAdder is a mock of MappingInfoGetAdder interface.
type MockMappingInfoGetAdder struct {
	ctrl     *gomock.Controller
	recorder *MockMappingInfoGetAdderMockRecorder
}

// MockMappingInfoGetAdderMockRecorder is the mock recorder for MockMappingInfoGetAdder.
type MockMappingInfoGetAdderMockRecorder struct {
	mock *MockMappingInfoGetAdder
}

// NewMockMappingInfoGetAdder creates a new mock instance.
func NewMockMappingInfoGetAdder(ctrl *gomock.Controller) *MockMappingInfoGetAdder {
	mock := &MockMappingInfoGetAdder{ctrl: ctrl}
	mock.recorder = &MockMappingInfoGetAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingInfoGetAdder) EXPECT() *MockMappingInfoGetAdderMockRecorder {
	return m.recorder
}

// AddNewMapping mocks base method.
func (m *MockMappingInfoGetAdder) AddNewMapping(ctx context.Context, id int64, originalUrl, shortUrl string) (domain.MappingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewMapping", ctx, id, originalUrl, shortUrl)
	ret0, _ := ret[0].(domain.MappingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewMapping indicates an expected call of AddNewMapping.
func (mr *MockMappingInfoGetAdderMockRecorder) AddNewMapping(ctx, id, originalUrl, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewMapping", reflect.TypeOf((*MockMappingInfoGetAdder)(nil).AddNewMapping), ctx, id, originalUrl, shortUrl)
}

// GetMappingByToken mocks base method.
func (m *MockMappingInfoGetAdder) GetMappingByToken(ctx context.Context, urlToken string) (domain.MappingInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappingByToken", ctx, urlToken)
	ret0, _ := ret[0].(domain.MappingInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMappingByToken indicates an expected call of GetMappingByToken.
func (mr *MockMappingInfoGetAdderMockRecorder) GetMappingByToken(ctx, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappingByToken", reflect.TypeOf((*MockMappingInfoGetAdder)(nil).GetMappingByToken), ctx, urlToken)
}

// MockOriginalUrlGetter is a mock of OriginalUrlGetter interface.
type MockOriginalUrlGetter struct {
	ctrl     *gomock.Controller
	recorder *MockOriginalUrlGetterMockRecorder
}

// MockOriginalUrlGetterMockRecorder is the mock recorder for MockOriginalUrlGetter.
type MockOriginalUrlGetterMockRecorder struct {
	mock *MockOriginalUrlGetter
}

// NewMockOriginalUrlGetter creates a new mock instance.
func NewMockOriginalUrlGetter(ctrl *gomock.Controller) *MockOriginalUrlGetter {
	mock := &MockOriginalUrlGetter{ctrl: ctrl}
	mock.recorder = &MockOriginalUrlGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOriginalUrlGetter) EXPECT() *MockOriginalUrlGetterMockRecorder {
	return m.recorder
}

// GetOriginalUrl mocks base method.
func (m *MockOriginalUrlGetter) GetOriginalUrl(ctx context.Context, shortUrl string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalUrl", ctx, shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetOriginalUrl indicates an expected call of GetOriginalUrl.
func (mr *MockOriginalUrlGetterMockRecorder) GetOriginalUrl(ctx, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalUrl", reflect.TypeOf((*MockOriginalUrlGetter)(nil).GetOriginalUrl), ctx, shortUrl)
}

// MockUrlTokenSetter is a mock of UrlTokenSetter interface.
type MockUrlTokenSetter struct {
	ctrl     *gomock.Controller
	recorder *MockUrlTokenSetterMockRecorder
}

// MockUrlTokenSetterMockRecorder is the mock recorder for MockUrlTokenSetter.
type MockUrlTokenSetterMockRecorder struct {
	mock *MockUrlTokenSetter
}

// NewMockUrlTokenSetter creates a new mock instance.
func NewMockUrlTokenSetter(ctrl *gomock.Controller) *MockUrlTokenSetter {
	mock := &MockUrlTokenSetter{ctrl: ctrl}
	mock.recorder = &MockUrlTokenSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlTokenSetter) EXPECT() *MockUrlTokenSetterMockRecorder {
	return m.recorder
}

// SetMapping mocks base method.
func (m *MockUrlTokenSetter) SetMapping(ctx context.Context, originalUrl, urlToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMapping", ctx, originalUrl, urlToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMapping indicates an expected call of SetMapping.
func (mr *MockUrlTokenSetterMockRecorder) SetMapping(ctx, originalUrl, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMapping", reflect.TypeOf((*MockUrlTokenSetter)(nil).SetMapping), ctx, originalUrl, urlToken)
}

// MockUrlTokenDeleter is a mock of UrlTokenDeleter interface.
type MockUrlTokenDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockUrlTokenDeleterMockRecorder
}

// MockUrlTokenDeleterMockRecorder is the mock recorder for MockUrlTokenDeleter.
type MockUrlTokenDeleterMockRecorder struct {
	mock *MockUrlTokenDeleter
}

// NewMockUrlTokenDeleter creates a new mock instance.
func NewMockUrlTokenDeleter(ctrl *gomock.Controller) *MockUrlTokenDeleter {
	mock := &MockUrlTokenDeleter{ctrl: ctrl}
	mock.recorder = &MockUrlTokenDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlTokenDeleter) EXPECT() *MockUrlTokenDeleterMockRecorder {
	return m.recorder
}

// DeleteMapping mocks base method.
func (m *MockUrlTokenDeleter) DeleteMapping(ctx context.Context, urlToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMapping", ctx, urlToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMapping indicates an expected call of DeleteMapping.
func (mr *MockUrlTokenDeleterMockRecorder) DeleteMapping(ctx, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMapping", reflect.TypeOf((*MockUrlTokenDeleter)(nil).DeleteMapping), ctx, urlToken)
}

// MockMappingInfoGetter is a mock of MappingInfoGetter interface.
type MockMappingInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMappingInfoGetterMockRecorder
}

// MockMappingInfoGetterMockRecorder is the mock recorder for MockMappingInfoGetter.
type MockMappingInfoGetterMockRecorder struct {
	mock *MockMappingInfoGetter
}

// NewMockMappingInfoGetter creates a new mock instance.
func NewMockMappingInfoGetter(ctrl *gomock.Controller) *MockMappingInfoGetter {
	mock := &MockMappingInfoGetter{ctrl: ctrl}
	mock.recorder = &MockMappingInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingInfoGetter) EXPECT() *MockMappingInfoGetterMockRecorder {
	return m.recorder
}

// GetMappingByToken mocks base method.
func (m *MockMappingInfoGetter) GetMappingByToken(ctx context.Context, urlToken string) (domain.MappingInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappingByToken", ctx, urlToken)
	ret0, _ := ret[0].(domain.MappingInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetMappingByToken indicates an expected call of GetMappingByToken.
func (mr *MockMappingInfoGetterMockRecorder) GetMappingByToken(ctx, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappingByToken", reflect.TypeOf((*MockMappingInfoGetter)(nil).GetMappingByToken), ctx, urlToken)
}

// MockMappingInfoLastIdGetter is a mock of MappingInfoLastIdGetter interface.
type MockMappingInfoLastIdGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMappingInfoLastIdGetterMockRecorder
}

// MockMappingInfoLastIdGetterMockRecorder is the mock recorder for MockMappingInfoLastIdGetter.
type MockMappingInfoLastIdGetterMockRecorder struct {
	mock *MockMappingInfoLastIdGetter
}

// NewMockMappingInfoLastIdGetter creates a new mock instance.
func NewMockMappingInfoLastIdGetter(ctrl *gomock.Controller) *MockMappingInfoLastIdGetter {
	mock := &MockMappingInfoLastIdGetter{ctrl: ctrl}
	mock.recorder = &MockMappingInfoLastIdGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingInfoLastIdGetter) EXPECT() *MockMappingInfoLastIdGetterMockRecorder {
	return m.recorder
}

// GetLastId mocks base method.
func (m *MockMappingInfoLastIdGetter) GetLastId(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastId", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastId indicates an expected call of GetLastId.
func (mr *MockMappingInfoLastIdGetterMockRecorder) GetLastId(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastId", reflect.TypeOf((*MockMappingInfoLastIdGetter)(nil).GetLastId), ctx)
}

// MockMappingInfoAdder is a mock of MappingInfoAdder interface.
type MockMappingInfoAdder struct {
	ctrl     *gomock.Controller
	recorder *MockMappingInfoAdderMockRecorder
}

// MockMappingInfoAdderMockRecorder is the mock recorder for MockMappingInfoAdder.
type MockMappingInfoAdderMockRecorder struct {
	mock *MockMappingInfoAdder
}

// NewMockMappingInfoAdder creates a new mock instance.
func NewMockMappingInfoAdder(ctrl *gomock.Controller) *MockMappingInfoAdder {
	mock := &MockMappingInfoAdder{ctrl: ctrl}
	mock.recorder = &MockMappingInfoAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingInfoAdder) EXPECT() *MockMappingInfoAdderMockRecorder {
	return m.recorder
}

// AddNewMapping mocks base method.
func (m *MockMappingInfoAdder) AddNewMapping(ctx context.Context, id int64, originalUrl, shortUrl string) (domain.MappingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewMapping", ctx, id, originalUrl, shortUrl)
	ret0, _ := ret[0].(domain.MappingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewMapping indicates an expected call of AddNewMapping.
func (mr *MockMappingInfoAdderMockRecorder) AddNewMapping(ctx, id, originalUrl, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewMapping", reflect.TypeOf((*MockMappingInfoAdder)(nil).AddNewMapping), ctx, id, originalUrl, shortUrl)
}

// MockMappingInfoUpdater is a mock of MappingInfoUpdater interface.
type MockMappingInfoUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockMappingInfoUpdaterMockRecorder
}

// MockMappingInfoUpdaterMockRecorder is the mock recorder for MockMappingInfoUpdater.
type MockMappingInfoUpdaterMockRecorder struct {
	mock *MockMappingInfoUpdater
}

// NewMockMappingInfoUpdater creates a new mock instance.
func NewMockMappingInfoUpdater(ctrl *gomock.Controller) *MockMappingInfoUpdater {
	mock := &MockMappingInfoUpdater{ctrl: ctrl}
	mock.recorder = &MockMappingInfoUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingInfoUpdater) EXPECT() *MockMappingInfoUpdaterMockRecorder {
	return m.recorder
}

// UpdateOriginalUrl mocks base method.
func (m *MockMappingInfoUpdater) UpdateOriginalUrl(ctx context.Context, urlToken, newOriginalUrl string) (domain.MappingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOriginalUrl", ctx, urlToken, newOriginalUrl)
	ret0, _ := ret[0].(domain.MappingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOriginalUrl indicates an expected call of UpdateOriginalUrl.
func (mr *MockMappingInfoUpdaterMockRecorder) UpdateOriginalUrl(ctx, urlToken, newOriginalUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOriginalUrl", reflect.TypeOf((*MockMappingInfoUpdater)(nil).UpdateOriginalUrl), ctx, urlToken, newOriginalUrl)
}

// MockMappingInfoDeleter is a mock of MappingInfoDeleter interface.
type MockMappingInfoDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockMappingInfoDeleterMockRecorder
}

// MockMappingInfoDeleterMockRecorder is the mock recorder for MockMappingInfoDeleter.
type MockMappingInfoDeleterMockRecorder struct {
	mock *MockMappingInfoDeleter
}

// NewMockMappingInfoDeleter creates a new mock instance.
func NewMockMappingInfoDeleter(ctrl *gomock.Controller) *MockMappingInfoDeleter {
	mock := &MockMappingInfoDeleter{ctrl: ctrl}
	mock.recorder = &MockMappingInfoDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingInfoDeleter) EXPECT() *MockMappingInfoDeleterMockRecorder {
	return m.recorder
}

// DeleteMappingInfo mocks base method.
func (m *MockMappingInfoDeleter) DeleteMappingInfo(ctx context.Context, urlToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMappingInfo", ctx, urlToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMappingInfo indicates an expected call of DeleteMappingInfo.
func (mr *MockMappingInfoDeleterMockRecorder) DeleteMappingInfo(ctx, urlToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMappingInfo", reflect.TypeOf((*MockMappingInfoDeleter)(nil).DeleteMappingInfo), ctx, urlToken)
}

// MockIdGenerator is a mock of IdGenerator interface.
type MockIdGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIdGeneratorMockRecorder
}

// MockIdGeneratorMockRecorder is the mock recorder for MockIdGenerator.
type MockIdGeneratorMockRecorder struct {
	mock *MockIdGenerator
}

// NewMockIdGenerator creates a new mock instance.
func NewMockIdGenerator(ctrl *gomock.Controller) *MockIdGenerator {
	mock := &MockIdGenerator{ctrl: ctrl}
	mock.recorder = &MockIdGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdGenerator) EXPECT() *MockIdGeneratorMockRecorder {
	return m.recorder
}

// GetNextId mocks base method.
func (m *MockIdGenerator) GetNextId(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextId", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextId indicates an expected call of GetNextId.
func (mr *MockIdGeneratorMockRecorder) GetNextId(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextId", reflect.TypeOf((*MockIdGenerator)(nil).GetNextId), ctx)
}
